### ISSUE TITLE
php artisan plugin:install  Renatio.DynamicPDF not working

### ISSUE THREAD

**Issue by kosmonowt** [mplodowski/dynamicpdf-plugin#46]
Hi there,

we're trying to install this plugin by CLI, since we are creating an install script with the help of offline/oc-bootstrapper.

During the plugin-installation by CLI with the standard command `php artisan plugin:install Renatio.DynamicPDF` we're receiving the following error (which we don't get during manual/backend install:

> [Symfony\Component\Debug\Exception\FatalThrowableError]
> Class 'Barryvdh\DomPDF\ServiceProvider' not found

is there any idea why?
Can someone reproduce this problem?
We could reproduce it in three different working environments (Mac, MAMP and homestead).
Also, after CLI-installation the whole site will be throwing this error.
It seems that the migrations were working, but somehow something is missing.
Any hints?

Thank you!

**Comment by mplodowski** [comment]
This plugin uses composer dependecies. You must go to plugin directory and run:

`composer install`

I don't know why `plugin:install` CLI command did not do it for you, maybe October bug.

**Comment by kosmonowt** [comment]
@mplodowski probably it's a bug.
Anyway I am installing multiple plugins that way – many of them also use vendor classes, but none of them throw this exception. All plugins but this one are cool with having the vendors installed after script execution.

I will also ask for support at rainlab, anyhow I believe there cloud also be a problem with your implementation of the service provider during boot, wich may not be compatible with the october-way of installing plugins CLI-wise. Somewhere around Plugin.php / boot() or classes/ServiceProvider.php / register()

**Comment by HugoWijdeveld** [comment]
Hi Renatio,

I'm having more or less the same problems here. I installed through the backend. Now the error report reads: "Class 'Barryvdh\DomPDF\ServiceProvider' not found". I'm using Windows10 and Xampp by the way, but I can't believe that would be relevant.

The composer dependencies are probably not installed because there is no composer.json file. Also I'm not sure what to with the suggestion to use commandline "vendor:publish", but maybe this makes sence once composer has done its job.

I'd really like to try out your plugin since you are getting such great reviews, but at the moment I'm stuck.

**Comment by mplodowski** [comment]
The problem was no `ext-gd` installed on October build server. This library was requirement for `dompdf` library and that is why composer could not install dependencies.

This was resolved by October staff.
