### ISSUE TITLE
Allow plugins to register PDF templates

### ISSUE THREAD

**Issue by cjbrooks12** [mplodowski/dynamicpdf-plugin#50]
It would be great to have an interface for other plugins to register PDF templates in a similar way to registering mail templates. For instance, a method like the following in your `Plugin.php` file:

```
public function registerPdfTemplates() {
    return [
        'vendor.plugin::pdf.template' => "PDF Description",
    ];
}
```

I have already begun work on this and would like to open a PR soon, but I wanted to open this as an issue for tracking purposes, and to invite feedback/suggestions.

**Comment by mplodowski** [comment]
Yeah, I think this will be a great feature.

For catalog structure it should follows October: https://octobercms.com/docs/services/mail#mail-views

But instead of `mail` folder it should be `pdf`.

I would probably use Plugin `boot` method to synchronise all file based templates with the currently added in database.

Let me know if you will have any questions.

I will wait for PR for this for further discussion.

**Comment by alvaro-canepa** [comment]
You can use `View::make` to get HTML content. And a generic PDF layout or template.

**Comment by mplodowski** [comment]
Done in version 4.0.2

Check documentation https://octobercms.com/plugin/renatio-dynamicpdf#pdf-content
