### ISSUE TITLE
Move backend menu to Settings

### ISSUE THREAD

**Issue by cjbrooks12** [mplodowski/dynamicpdf-plugin#51]
It seems like the backend menu for this plugin should live under the Settings screen rather than on the main navigation menu, and maybe layout the UI to match the Mail templates section as well. If this would be desired, I'd be willing to make these changes and open a PR for it.

**Comment by mplodowski** [comment]
When I wrote first version of the plugin indeed menu was inside Settings area.

This was change some time ago by PR. The reason back then was that Settings has issues with separating templates and layouts. This was fixed by October team.

If you make UI like Mail Templates than I will accept this PR.
